rogue:fix the tanlent "mace specialization"
wowsims/wotlk pull request #3402
Opened 2023-07-31 12:36 UTC by joexi

rogue talent "mace specialization" will cause 15% armorpen, when you get a mace in main-hand and a sword in off-hand, simc will only counting this 15% armorpen in main-hand melee, but in real game, the off-hand melee will also benefit with "mace specialization" in case you has a mace in main-hand

2023-08-01 21:04 UTC, vigo2 commented
Do you have logs or screenshots to support this claim? I couldn't find anything about this on the rogue discords.
If it's enough to wield a mace in either hand for "Mace Specialization" to apply, the ArPen bonus could be added to `Unit.stats[stats.ArmorPenetration]` directly instead of using `BonusSpellPenetration`.

2023-08-02 02:00 UTC, joexi commented
As a rogue player for decades, i promise this feature about mace is 100% ture, here is my screenshot about using different weapon, and with no trinket and weapon enchantment to make results stable,all weapons are trash weapons and offer zero stats
situation NO.1:
skill:shiv
mace specialization: 5/5
main-hand weapon:sword
off-hand weapon:dagger
dmg per cast:779
times:100




situation NO.2:
skill:shiv
mace specialization: 5/5
main-hand weapon:mace
off-hand weapon:dagger
dmg per cast:807
times:103


situation NO.3:
skill:sinister strike
mace specialization: 5/5
main-hand weapon:sword
off-hand weapon:dagger
dmg per cast :1484
dmg per cast (crit):4284
times:100


situation NO.4:
skill:sinister strike
mace specialization: 5/5
main-hand weapon:sword
off-hand weapon:mace
dmg per cast:1517
dmg per cast(crit):4352
times:100



.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wowsims/wotlk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月2日(星期三) 凌晨5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wowsims/wotlk] rogue:fix the tanlent "mace specialization" (PR #3402)





 
Do you have logs or screenshots to support this claim? I couldn't find anything about this on the rogue discords.
 If it's enough to wield a mace in either hand for "Mace Specialization" to apply, the ArPen bonus could be added to Unit.stats[stats.ArmorPenetration] directly instead of using BonusSpellPenetration.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-08-02 02:41 UTC, joexi commented
acturely, this is a common knowledge in cn,cause we have a loooooong time tbc(with wotlk talent) years ago,&nbsp;
many rogues use build like "Hand of the Deceiver" + "Any mace" to achieve high dps


.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "."                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月2日(星期三) 上午10:00
***@***.***&gt;;

主题:&nbsp;回复： [wowsims/wotlk] rogue:fix the tanlent "mace specialization" (PR #3402)



As a rogue player for decades, i promise this feature about mace is 100% ture, here is my screenshot about using different weapon, and with no trinket and weapon enchantment to make results stable,all weapons are trash weapons and offer zero stats
situation NO.1:
skill:shiv
mace specialization: 5/5
main-hand weapon:sword
off-hand weapon:dagger
dmg per cast:779
times:100




situation NO.2:
skill:shiv
mace specialization: 5/5
main-hand weapon:mace
off-hand weapon:dagger
dmg per cast:807
times:103


situation NO.3:
skill:sinister strike
mace specialization: 5/5
main-hand weapon:sword
off-hand weapon:dagger
dmg per cast :1484
dmg per cast (crit):4284
times:100


situation NO.4:
skill:sinister strike
mace specialization: 5/5
main-hand weapon:sword
off-hand weapon:mace
dmg per cast:1517
dmg per cast(crit):4352
times:100



.
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "wowsims/wotlk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月2日(星期三) 凌晨5:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wowsims/wotlk] rogue:fix the tanlent "mace specialization" (PR #3402)





 
Do you have logs or screenshots to support this claim? I couldn't find anything about this on the rogue discords.
 If it's enough to wield a mace in either hand for "Mace Specialization" to apply, the ArPen bonus could be added to Unit.stats[stats.ArmorPenetration] directly instead of using BonusSpellPenetration.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-08-02 03:37 UTC, joexi commented
seems screenshot from email cant display in rightway, i post the screenshot here again @vigo2 
![1](https://github.com/wowsims/wotlk/assets/3711488/1753ea32-f674-4868-ade5-ebbda561a523)
![2](https://github.com/wowsims/wotlk/assets/3711488/08b563cd-ca6f-491e-a159-06b4ae409ac8)
![3](https://github.com/wowsims/wotlk/assets/3711488/7670c808-c4dd-4449-859c-7c47bfe6a487)
![4](https://github.com/wowsims/wotlk/assets/3711488/9b7a96fa-37aa-4d9c-8a95-954b59c33f76)

2023-08-04 20:39 UTC, vigo2 commented
Thank you, this seems to be official knowledge now ;)

2023-08-04 21:24 UTC, vigo2 requested changes

2023-08-04 21:24 UTC, vigo2 commented on sim/rogue/talents.go
> +				if spell.ProcMask.Matches(core.ProcMaskMeleeMH) || spell.ProcMask.Matches(core.ProcMaskMeleeOH) {
Please use `rogue.AddStat(stats.ArmorPenetration, ...)` if a mace is equipped in either hand, so the actual amount of ArPen is displayed in the "Stats" panel. (The two "mace cases" here and below then simply set a "anyMaceEquipped" bool or so.)

2023-08-04 21:32 UTC, vigo2 commented on sim/rogue/talents.go
> +				if spell.ProcMask.Matches(core.ProcMaskMeleeMH) || spell.ProcMask.Matches(core.ProcMaskMeleeOH) {
Also, when using maces in both MH and OH, the `OnSpellRegistered` handlers would wrongly add Mace Spec's `BonusArmorPenRating` twice.

2023-08-08 09:32 UTC, closed without merging

2023-08-08 13:36 UTC, vigo2 commented
@joexi Did you close this by accident?

2023-08-16 19:49 UTC, catszeid commented
Issue is fixed with commit [here](https://github.com/wowsims/wotlk/commit/0fecdbfa644a3bc6329a1b20a0e131d597171f9d).